.gitmodules
SSH authentication fails when users try to install their own forks using pip
but HTTPS authentication seems to work just fine
=> Update URLS in .gitmodules to use https instead of ssh

example_scripts/get_example_file.py, pymzml/obo.py, pymzml/run.py, test/test_deconvolution.py, test/test_obo.py, test/test_readChromMzML.py
When parsing mzML files with spectra or chromatograms in them, it's useful to know how many spectra or chromatograms are included in the file.
The existing code already counted spectra but did not count chromatograms. The following pull requests adds this functionality, modeled closely on the logic around `spectrum_count`. As a bonus, I have also added unit tests, fixed bugs/breaks in existing uint tests, made a few more files conform to PEP8, and broken up a variety of large, monolithic functions into smaller, more reusable components.
If this request is accepted, it probably merits a bump to `v0.7.7`.
=> Feature: add chromatogram count

setup.py
- this enables `setup.py bdist_wheel`, which eases pypi upload
=> Add support for generating python wheel

pymzml/version.py, setup.py
so far the version number was stored in a version.txt as well as version.py,
only verison.py is used now
=> set version via version.txt

example_scripts/extract_ion_chromatogram.py, example_scripts/get_precursors.py, example_scripts/simple_parser.py, pymzml/plot.py, pymzml/spec.py, tests/main_spec_test.py, tests/ms2_spec_test.py
So far, spec.scan_time reports the retention time in minutes, performing an internal conversion into minutes, depending on the unit defined in the mzML. This fails at the moment if the unit is not minute or second.
The function has been modified to report the retention time and its unit (as defined in the mzML).
In order to keep the possibility to get the retention time in minutes, the function spec.retention_time_in_minutes() has been created, using the same conversion as before.
The tests and example scripts have been changed accordingly.
Besides this, setting xmax and ymax in plot.py has been corrected.
=> modified scan_time to report retention time and its unit

pymzml/obo.py
The encoding name contained a typo. After fixing the typo, the bug reported in #108 was resolved.
=> fix:Typo in encoding name

pymzml/run.py
this adds a 0 key to `run.Reader.ms_precisions` to tolerate non-MS based spectra like UV absorbance. The precision default value is currently 0.001 which seems to be fine for my usage but please let me know if that should change and I'll tweak it.  
fixes #119
=> added 0 key for UV spectra

pymzml/run.py
Potential fix for #121 .
When setting MSn_Precision when initialising the reader, MS2 and MS3 precision are set.
=> set ms3 precision when setting MSn_Precision in run

pymzml/run.py
This makes it easier to close the file_object handle https://github.com/pymzml/pymzML/blob/7f01356d409b77c809eb751431064ff5c5ba64bc/pymzml/run.py#L114 and avoids ```ResourceWarning:unclosed file``` errors when you loop through a list of mzml files or when you 'reload' the reader object.
=> Add 'close' function to reader class

pymzml/run.py, tests/main_reader_test.py
the Reader class can now be used as the following:
```
with pymzml.run.Reader(file) as mzml_reader:
for spec in mzml_reader:
```
this ensures that the underlying file handlers are properly closed
=> Implement with context for pymzml.run.Reader

pymzml/file_classes/standardMzml.py
- dont close seekers so the underlying binary stream is not closed
- related to #145
=> Fix bug with random access in binary IO streams

pymzml/plot.py
- use plotly.subplots instead of plotly.tools for creating subplots
=> Fix plotly deprecation warnings

pymzml/spec.py, tests/ms2_spec_test.py
- when accessing cvParams in the spectrum class, return True if cvParam exists and does not have a value assigned
- as before, None if returned if not result for the given query could be found
=> Improve accession of cvParams in spec

pymzml/spec.py
Fix python3.8 syntax warning for improper string comparisons
- solves #242
=> fix string comparisons from `is` to `==`

pymzml/spec.py, tests/ms2_spec_test.py
- add precursor id to `selected_precursor` property output and remove `precursor` property
- adapt unittest for new output
- makes #255 redundant
- fixes #254
=> Restructure precursor information

pymzml/spec.py
It is valid to have millisecond for retention time units as shizmadzu instruments report this. Small code update to allow for this. 
```
<scanList count="1">
<scan>
<cvParam cvRef="MS" accession="MS:1000016" name="scan start time" value="1583100" unitCvRef="UO" unitAccession="UO:0000028" unitName="millisecond"/>
</scan>
</scanList>
```
=> Adding support for millisecond retention time unit

pymzml/file_classes/standardMzml.py, pymzml/regex_patterns.py, tests/regex_test.py
mzml files in both formats can now be parsed:
`<spectrum id="controllerType=0 controllerNumber=1 scan=1" index="0" defaultArrayLength="1100">`
`<spectrum index="0" id="controllerType=0 controllerNumber=1 scan=1" defaultArrayLength="917">`
=> modified regex to work with id and index regardless of order

pymzml/spec.py
Fixes spectra addition when the spectrum that is being added to has no "reprofiled" key in self._peak_dict
I was trying to add spectra together and it did not work - so I introduced suggested changes
=> generate reprofiled in Spectrum.__add__ if not present.

pymzml/spec.py
Methods getchildren() and getiterator() in the ElementTree module have been removed. They were deprecated in Python 3.2. Use functions list() and iter() instead. (https://docs.python.org/3/library/xml.etree.elementtree.html)
=> Fixes deprecated .getiterator()

pymzml/spec.py
When subtracting two spectra, the subtracted one has to have reprofiled peaks. this is not necessarily the case. If no reprofiled peaks are there, create them, this fixes the error
=> fix error when subtracting two spectra

pymzml/obo.py, pymzml/run.py, pymzml/spec.py
This PR addresses the issue described in #333.
- provides a caching mechanism based on obo version for OboTranslator
- allows Spectrum and Chromatogram to be instantiated with a obo_version as kwarg
Closes #333
=> Refactor spec spectrum
