pymzml/pymzML

pymzml/run.py

Fix issue with Writer class, that results in only one spectrum output
Added implicit copy and dereferncing of spectrum prior to adding to XML tree

Writer fix

---

pymzml/spec.py

- include elements under "precursor" tag
- reads in userParam tags

[FEATURE] improve precursor parsing

---

pymzml/run.py
tests/main_reader_test.py

- added support for  run_id and start_time
- updated the tests to test new code

PYMZML-80 - increase metadata

---

pymzml/spec.py

Solves some compatibility issues.

Modified selected_precusors property for incomplete precursor data

---

pymzml/utils/utils.py

Fix utils.utils.index_gzip which was broken due to a changed regex
Thanks at @mobiusklein for pointing this out!

fix issue #103

---

pymzml/spec.py

Checks if binary tag is empty and returns either an empty numpy array or an empty list
@StSchulze can you test this with your file?

fix issue #102 when crashing due to empty spectra

---

docs/source/code_inc/extract_ion_chromatogram.inc
docs/source/example_scripts.rst
example_scripts/extreme_values.py
example_scripts/multi_threading_file_compression.py
pymzml/spec.py

Edited formatting of some error messages.

Small speed optimization in spectrum.extreme_values()

---

docs/source/code_inc/plotAspec_2.inc
example_scripts/compare_spectra.py
example_scripts/deprecation_check.py
example_scripts/download_obo_database.py
example_scripts/extract_ion_chromatogram.py
example_scripts/get_example_file.py
example_scripts/get_precursors.py
example_scripts/has_peak.py
example_scripts/plot_chromatogram.py
example_scripts/plot_spectrum.py
example_scripts/plot_spectrum_with_annotation.py
example_scripts/polarity.py
example_scripts/queryOBO.py
pymzml/__init__.py
pymzml/decoder.py
pymzml/file_classes/indexedGzip.py
pymzml/file_classes/standardGzip.py
pymzml/file_classes/standardMzml.py
pymzml/file_interface.py
pymzml/ms_numpress.py
pymzml/obo.py
pymzml/plot.py
pymzml/run.py
pymzml/spec.py
requirements.txt
setup.py

This commit makes some reasonable assumptions about the use cases of pymzML, and uses those
assumptions to significantly clean up the code, simplify it, and make it more flexible.
The assumptions are:
1. The library should only run on python >= 3.4
2. Numpy is no longer optional
The first is explicitly stated by the project, and the second is an easy criterion: no one doing
calculation on mass spec should _not_ have numpy installed; especialyl if they are using python3,
it is virtually impossible to have a python system that does not have a successful version of numpy.
In addition to the above assumptions, the following flexibility improvements are implemented.
3. Plotly should not be made a default requirement: it often requires many other packages, which
systems may not want to install, …

Standardize dependencies and imports

---

README.rst

- change the suffix of CONTRIBUTING from md to rst

Fix filename in README

---

pymzml/plot.py
pymzml/spec.py
tests/main_spec_test.py

- fixed averaging of spectra
- supplied tests for averaging spectra
- fix for #98

Fix bugs when averaging spectra

---

CONTRIBUTING.rst
pymzml/plot.py
pymzml/spec.py
requirements.txt
setup.py
tests/main_spec_test.py
tests/ms2_spec_test.py

- add ability to deconvolute spectra using ms_deisotope (https://github.com/mobiusklein/ms_deisotope)
- add first test
- add ms_deisotop in requirements.txt
addresses #60

Add deconvolution functionality

---

.travis.yml
requirements.txt

tox is used for development only.

Remove tox from runtime dependencies

---

pymzml/spec.py

Move warning for missing ms_deisotope to deconvolute method

---

example_scripts/gzip_mzml.py
example_scripts/spectrum_viewer.py
requirements.txt

A spectrum viewer based on Dash I have coded some time ago. The idea was to have a very simple and fast viewer based on pymzML and Dash.
Works very smoothly on igzip files, thanks to the quick jumps to specific spectra. 
Let me know what you think!

Added spectrum viewer example script using Dash

---

tests/main_reader_test.py

- Add test to ensure setting MS_precisions dict in reader propagates to
returned spectra

Test setting of measured precision

---

README.rst
setup.py

- Specify python3.5 as minimal python version in setup.py and README

Drop python3.4 support

---

pymzml/run.py
tests/main_reader_test.py

- When all spectra are iterated, reset the iter to allow another round of iteration

Reset iter after StopIteration

---

pymzml/file_classes/standardMzml.py

remove legacy code

---

pymzml/spec.py
tests/main_spec_test.py

- get_tims_tof_ion_mobility
- get_array for getting any available array
- get_all_arrays_in_spec() retrieve a list of all binary array names in current spec

Implement methods for retrieving ion mobility arrays

---

.travis.yml
README.rst
setup.py
tox.ini

Should come with a bump to version 2.5.0

require python >=3.7

---

pymzml/file_classes/standardMzml.py

Fix issue with parsing multiple chromatograms

---

pymzml/spec.py
tests/ms2_spec_test.py

Add element precursor as PR from Wolfgang Colsman
